# Title of the site
site_name: "Reqsnaked"

# Description of the site
site_description: Reqsnaked python library guide

# URL for pages editing
repo_url: https://github.com/deknowny/reqsnaked/tree/main/

# Branch chosen when routing to repository
remote_branch: main

# Where md files are stored
docs_dir: guide

# Site's content
nav:
  - Home: index.md
  - User Guide:
    - Introduction: user-guide/index.md
    - Understand the basics: user-guide/basics.md
    - Headers: user-guide/headers.md
    - Query string: user-guide/query-string.md
    - Forms: user-guide/form.md
    - JSONs: user-guide/json.md
    - Authentication: user-guide/auth.md
    - Multipart: user-guide/multipart.md
    - Cookies: user-guide/cookies.md
    - Raw response: user-guide/raw-response.md
    - Chunks (streaming response): user-guide/chunks.md

  - For contributors: contributing.md
  - Support us: suuport.md



# Theme preference. Use `mkdocs-material`
theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Ubuntu
    code: Monaco
  features:
    - header.autohide
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - search.highlight
    - search.share



extra:
  analytics:
    provider: google
    property: G-6T0WXKZ5S5


plugins:
  # - social:
  #     cards_dir: assets/
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

extra_css:
  - css/theme.css

extra:
  version:
    provider: mike
    default: latest
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

# Material extensions
markdown_extensions:
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage
